global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets: ['10.10.10.2:9090']  #prom-client (gotta pull here)

  - job_name: postgresql
    static_configs:
      - targets: ['10.10.10.2:9187'] 