version: '3'

services: 
  emqx:
    image: emqx:5
    deploy:
      replicas: 2 
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.emqx-broker == true
        max_replicas_per_node: 1
    ports:
      - target: 1883
        published: 1883
        mode: ingress
        protocol: tcp
    healthcheck:
      test: ["CMD", "emqx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
